name: Build and Release JAR

on:
  push:
    branches:
      - master # اجرا برای هر push روی شاخه main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Build the JAR
      - name: Build JAR
        run: ./gradlew clean build

      # Upload the JAR as an artifact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          name: app-jar
          path: build/libs/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Download the built JAR artifact
      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: app-jar

      # Generate a timestamp-based tag
      - name: Generate tag
        id: generate_tag
        run: echo "::set-output name=tag::v$(date +'%Y%m%d-%H%M%S')"

      # Publish Release
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: app-jar
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.generate_tag.outputs.tag }} # استفاده از تگ بر اساس زمان
          name: "Release ${{ steps.generate_tag.outputs.tag }}"
          body: |
            This release contains the latest build of the project.
            Download the JAR file below.
          draft: false
          prerelease: false
